### ISSUE TITLE
Visual Results Display and Runtime (FPS)

### ISSUE THREAD

**Issue by momei123** [Eezekiel/SiT-MLP#1]
Hello, 
can you provide some visual results and runtime (FPS)?

**Comment by zhshj0110** [comment]
Thanks for your interest.
The code has been released. For the visual results, you can refer to our [manuscript](https://arxiv.org/abs/2308.16018). For the runtime (FPS), you can easily get the experimental results, according to the released code.
If you have further questions, feel free to issue.
